# Generated by Django 4.0.2 on 2022-03-01 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mp_nodes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treesection',
            name='parent',
        ),
    ]
